### ISSUE TITLE
Formula assumes Java installed

### ISSUE THREAD

**Issue by tharoules-ever** [saltstack-formulas/jenkins-formula#67]
Hi,

When running this formula on a very clean box, such that it minimal install doesn't include a Java version.  The formula breaks in an somewhat goofy way:  Jenkins has dependency on Java to run.  Perhaps include a test that Java is installed and at some reasonable minimal version ?
or a doc change that suggests including: https://github.com/saltstack-formulas/java-formula

**Comment by myoung34** [comment]
It's not really goofy, java is roll your own since you may need the JDK (if your jenkins master runs tests), JRE, and whether you choose Sun or OpenJDK/OpenJRE

If you look in the [kitchen yaml](.kitchen.yml) you'll see some usage with the sun-java-formula

I'm open to a PR to include this, but there are in fact tests that include java as a dependency

**Comment by tharoules-ever** [comment]
Agreed, maybe a documentation change is the way to go, suggesting that it is as you say: byoj.  (Bring your own java)

After a bit of thought, it can't be just a simple test for java installed as if you use a native os package like apt or yum may have different dependencies on Java versions that you can't predict and change, and having a lot of if else statements in there would make this ugly.

**Comment by myoung34** [comment]
If you put a PR into master for README.rst I'd be happy to merge it, you can use some snippets from the pillar.example or .kitchen.yml if you like

**Comment by myoung34** [comment]
Gonna close this as BYOJ, as well as tests passing with java pre-req. feel free to reopen if it becomes open for discussion again
